title:
  ru: Библи&shy;отека Пономаря
  en: Ponomar Library

keywords:
  ru: "церковнославянский язык, церковно-славянский язык, старославянский язык, глаголица, литургика, Типикон, устав, историческая литургика, палеография"
  en: "Church Slavic, Church Slavonic, Old Church Slavonic, Old Slavonic, Old Church Slavic, Glagolitic, liturgics, typicon, ustav, paleography, palaeography"

authors:
  ru: Александр Андреев, Михаил Крутиков, Всеволод Еникеев
  en: Aleksandr Andreev, Mike Kroutikov, Vsevolod Yenikeev

google_analytics: "UA-12187460-2"
 
markdown:
  kramdown

plugins:
  - jekyll-sitemap
